### ISSUE TITLE
Training with the provided dataset

### ISSUE THREAD

**Issue by AndroYD84** [stonyhu/DanceRevolution#1]
Hello! Thank you very much for sharing your project, your results look very exciting! I guess the dataset needs to be preprocessed first using "prepro.py" by pointing it to where the dataset is located, but after running it for a while I get the following error message:

```
---------- Align the frames of music and dance ----------
...
music -> (1801, 438), dance -> (1800, 274), min_seq_len -> 1800
---------- Save to text file ----------
Traceback (most recent call last):
  File "prepro.py", line 190, in <module>
    save(args, musics, dances)
  File "prepro.py", line 155, in save
    assert len(fnames) == len(musics) == len(dances), 'alignment'
AssertionError: alignment
```

Is there any solution for this? I'd really appreciate more information about the training procedure.

**Comment by Jiankai-Sun** [comment]
Same AssertionError

**Comment by dukecyto** [comment]
Same error here.
Looking at the code, these lines really puzzle me:
https://github.com/stonyhu/DanceRevolution/blob/0e8f0d83c2b86a0a709ccdddcb361c9453c0ed8a/prepro.py#L132-L137
Apparently these lines will multiply the number of musics and dances by three, making the assert to fail.
The intent there is also incomprehensible. Why do you slice the data at frame % 3 == 0, frame % 3 == 1, and frame % 3 == 2?
If you are trying to align the number of frames, why not just slice?

**Comment by CrystalWang1225** [comment]
I simply commented out j%3 == 2 and j%3 ==1 lines, and it worked

**Comment by aryanna384** [comment]
when I ran prepro.py I met with:
No such file or directory: '/mnt/data/dance-data/youtube/audio_1min'
Did I lack of data?where can I down them?

**Comment by stonyhu** [comment]
Thank you for your interests in our work. We have updated `prepro.py` and `README.md`, please follow the instruction to try again.
