### ISSUE TITLE
How can I use my own music to generate dance?

### ISSUE THREAD

**Issue by aryanna384** [stonyhu/DanceRevolution#7]
Hi, thanks for your great work, how can I use my own music to generate dance?

**Comment by stonyhu** [comment]
@aryanna384 Hi, I have updated `prepro.py` and `README.md` to help you on this issue.

**Comment by aryanna384** [comment]
Thanks for your reply! I’m trying now. And what's the meaning of BOS_POSE in pose.py, initial of the skeleton? How does it get?
`BOS_POSE = np.array([
    -0.00647944, -0.540766, -0.00655532, -0.3829, -0.0862469, -0.388304, -0.107649, -0.137507, -0.0648178,
    0.0423361, 0.0791047, -0.382726, 0.0882645, -0.148286, 0.0699688, 0.0641147, 0.0056175, 0.05319,
    -0.0464647, 0.0476973, -0.0465082, 0.467254, -0.031224, 0.854397, 0.0576743, 0.0585055, 0.0394117,
    0.478282, 0.0208931, 0.854322, -0.0158758, -0.568058, 0.0147899, -0.568106, -0.0465137, -0.568036,
    0.0391742, -0.562693, 0.0209782, 0.936187, 0.0424097, 0.930442, 0.0148087, 0.886806, -0.0249588, 0.935932,
    -0.0434218, 0.935805, -0.0280986, 0.886854
])
`
